# Generated by Django 5.1.5 on 2025-01-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(default='English', max_length=200),
            preserve_default=False,
        ),
    ]
